I13 user removed
AgoraSpaceDAO/telegram-runner pull request #18
Opened 2021-06-16 18:18 UTC by schronck

Closes #13

2021-06-16 18:59 UTC, dezsim commented on src/service.ts
> +  communityId: string | undefined
We should identify the communityId as an optional parameter instead of `string | undefined`.
Like this way: `communityId?: string`.

2021-06-16 19:03 UTC, dezsim commented on src/service.ts
> +  communityIds.map((commId) => {
Why are we using the `map` operator here? We are returning true and the end of the function and we are not mapping anything. I would reconsider using `forEach` instead of `map`.

2021-06-16 19:10 UTC, dezsim commented on src/service.ts
> +  const chatId = message.chat.id;
Maybe we could use this here, because later on we don't really use the `message` variable.
`const chatId = ctx.message.chat.id;`

But in my opinion, we don't really need to destructure the ctx object, because we are using chatId only once in the if sentence at `line 123`.

2021-06-16 19:26 UTC, dezsim approved these changes

2021-06-16 23:40 UTC, dovalid requested changes

2021-06-16 23:40 UTC, dovalid commented on src/service.ts
> +      `Hey ${firstName}!\nDo you really want to *LEAVE ${commName}*?`,
I get the cheeky tone but it's not inlined with the rest of the product so should rather be "You'll be kicked from every Agora group. Are you sure?"

(Though every content will be carefully redesigned when we'll have the capacity)

2021-06-16 23:40 UTC, dovalid commented on src/service.ts
> +const leaveCommunity = async (
I think this function abstracts at the wrong level. There should be a leaveCommunityAction as I mentioned in one of my comments, which just fetches the endpoint, and an onBotBlocked or something like that (which's trigger isn't wired up yet), which does what this does when justThisOne is false. If you want, you could abstract just the axios call itself into "fetch[whatever we'll end up calling the endpoint]"

2021-06-17 14:31 UTC, dovalid commented on src/Main.ts
> +    // user confirmed leaving the community
I thought the confirmLeaveCommunityAction should be the first which triggers the confirmation, and the leaveCommunityAction that actually fetches the endpoint. Also the payload should be confirm_leave_[...] for the confirmLeaveCommunityAction

2021-06-17 14:31 UTC, dovalid commented on src/api/types.ts
> +  id: number;
Change back to string as we discussed

2021-06-17 14:31 UTC, dovalid commented on src/service.ts
> +  communityIds: number[]
It should just be leaveCommunity excepting a single communityId and calling the endpoint with it. The forEach should be in onBlocked, outside the function call

2021-06-17 16:45 UTC, dovalid approved these changes

2021-06-17 17:07 UTC, merged